server:
  port: 8080

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://ip:3306/ChatRoomTest?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password:
  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait=10s: 10s
        min-idle: 0
        max-idle: 8
    timeout: 500

authorization:
  token:
    url: /user/login